### ISSUE TITLE
Suggestion: Report link activity as a custom event.

### ISSUE THREAD

**Issue by tdejneka** [gwww/hass-upb#1]
Currently, link activity is reported as a scene's state-change. The resulting event simply indicates the scene changed state.

I suggest defining a custom event and using it to report the details of a link's activity.

Examples of potential custom UPB events:

```
{
    "event_type": "upb_event",
    "data": {
        "link": "2",
        "name: "All Exterior Lights"
        "command": "deactivate"
    },
    "origin": "LOCAL",
    "time_fired": "2020-02-01T16:00:00.123456+00:00",
    "context": {
        "id": "abcdefghijkl123456789",
        "parent_id": null,
        "user_id": null
    }
}
```

```
{
    "event_type": "upb_event",
    "data": {
        "link": "6",
        "name: "All Interior Lights"
        "command": "goto",
        "brightness_pct": 50,
        "fade_rate": 2
    },
    "origin": "LOCAL",
    "time_fired": "2020-02-01T17:00:00.123456+00:00",
    "context": {
        "id": "123456789mnopqrstuv",
        "parent_id": null,
        "user_id": null
    }
}
```

Basically the `data` would report, at a minimum, the link's number, its name (merely as a convenience for the end-user), and the command. Depending on the command, additional properties may be required such as brightness_pct and fade_rate (and possibly effects such blink).

**Comment by bbrendon** [comment]
Seems sound. I would rename event_type from `upb_event` to `upb_link` or maybe just simply `upb`. Using the term "event" in the event_type is repetitive.

**Comment by gwww** [comment]
Here's my suggestion:
```
{
    "event_type": "upb.link_changed",
    "data": {
        "entity_id": "scene.all_interior_lights",
        "command": "Goto",
        "brightness_pct": 50,
    }
}
```
Entity ID preferred over using name and link number by Hass folks. From entity you can get name, etc.

**Comment by tdejneka** [comment]
The examples I provided were based on how events are reported by the Deconz and ZHA integrations. Those two integrations don't indicate the event's specifics in `event_type` and simply report the integration;s name like: "deconz_event" and "zha_event". All the of the event's details are found in its `data`.

In contrast, the z-wave integration does use `event_type` to indicate something specific about the event (beyond just the integration's name). For example, there's this event [zwave.scene_activated](https://www.home-assistant.io/docs/z-wave/events/#zwavescene_activated) and its `data` reports `entity_id` and `scene_id`. The equivalent for UPB would be something like:

```
{
    "event_type": "upb.scene_activated",
    "data": {
        "entity_id": "scene.all_interior_lights",
        "link_id": "2"
    }
}
```
Along with its counterpart:
```
{
    "event_type": "upb.scene_deactivated",
    "data": {
        "entity_id": "scene.all_interior_lights",
        "link_id": "2"
    }
}
```
Obviously `link_id` is not required but can be included for the user's convenience (trigger can match on either `entity_id` or `link_id` depending on the user's preference).

Following the z-wave integration's model, another event would be required to report the case of changing the scene's level (and fade-rate):

```
{
    "event_type": "upb.scene_changed",
    "data": {
        "entity_id": "scene.all_interior_lights",
        "link_id": "2",
        "brightness_pct": 50,
        "fade_rate": 3
    }
}
```
There can also be dedicated events for other scene activities such as `upb.scene_blink`, `upb.scene_start_fade`, and `upb.scene_stop_fade`,

**Comment by gwww** [comment]
What is the preference... upb.sceme_command with data containing the command OR upb.scene_activate, upb.scene_deactivate, etc. I'm easy either way.

**Comment by tdejneka** [comment]
I'd say that if there were a bajillion different kinds of possible event types then it's more compact to use one generic event type and put the specifics in the event's data. That seems to be the design choice for the Deconz and ZHA integrations. 

If there are only a few specific event types then they can be individually defined. The z-wave integration appears to follow that course. I count only seven distinct [Z-wave events](https://www.home-assistant.io/docs/z-wave/events).

If we have a specific event_type then triggering for "scene activated" is simply this:

```
- alias: 'Interior Lights Scene Activated'
  trigger:
    platform: event
    event_type: upb.scene_activated
    event_data:
      entity_id: scene.all_interior_lights
  action:
    <do something>
```
If the event_type is more generic then the trigger needs to also select the command we want:
```
- alias: 'Interior Lights Scene Activated'
  trigger:
    platform: event
    event_type: upb.scene_command
    event_data:
      entity_id: scene.all_interior_lights
      command: "activate"
  action:
    <do something>
```
The only real difference between the two is that the second one must inspect every "scene_command" event (to find a matching entity_id and command) whereas the first one only needs to inspect "scene_activated" events (to find a matching entity_id). 

Given that I count just six event types to handle all scene activities:

    upb.scene_activated
    upb.scene_deactivated
    upb.scene_changed
    upb.scene_blinking
    upb.scene_startedfade
    upb.scene_stoppedfade

my preference is for this format.

**Comment by tdejneka** [comment]
One more thing:

The only reason I used:

- scene_activated
- scene_deactivated
- scene_changed
- scene_blinking
- scene_startedfade
- scene_stoppedfade

instead of:

- scene_activate
- scene_deactivate
- scene_change
- scene_blink
- scene_startfade
- scene_stopfade

is because if in the future you were to ever add the ability to use an event to _command_ the UPB integration then the user could write this:
```
  action:
    event: upb.scene_blink
    event_data:
      entity_id: scene.all_exterior_lights
```
`scene_blink` is an event to command the integration whereas `scene_blinking` is a status report from the integration.

If there's no chance of ever adding this functionality (because it can't be done, or another naming convention could be used, or it's deemed to be redundant and unnecessary, or you simply have no desire to implement it) then it doesn't matter if the event_type uses "activate" vs "activated".

**Comment by gwww** [comment]
Naming being consistent throughout is nice because it generally leads to less code. The downside is less readability `scene_activated` reads much nicer than `scene_activate`. I can go either way but have a leaning towards `scene_activated` as I prefer end-user ease of understanding.

I give you veto vote on this one :) Pick which one you would like and I will do it!

BTW, code is written and somewhat tested. It should be uploaded tonight.

**Comment by tdejneka** [comment]
I vote for `scene_activated`, `scene_deactivated`, `scene_changed`, etc.

**Comment by gwww** [comment]
Done. Code already uploaded :)  Although `scene_changed` isn't an event unless I'm missing something.

**Comment by tdejneka** [comment]
Let's consider what happens when a source, other than Home Assistant, issue an Activate command for link 7.

1. The UPB integration detects the command.
2. It knows which devices are associated with link 7 (by way of the UPE file).
3. It also knows how all the devices are programmed to respond to Activate Link 7.
4. It set all corresponding entities to the appropriate state.
5. Finally, it posts a `upb.scene_activated` event.

Now let's consider what happens when some other source issues a Goto level 75 for link 7.

1. The UPB integration detects the command.
2. It knows which devices are associated with link 7 (by way of the UPE file).
3. It knows all the devices have been set to level 75.
4. It set all corresponding entities to brightness_pct = 75.
5. Finally, it posts a `upb.scene_changed` event.

In the same way that `scene_activated` allows an end-user to know when an external source activated a scene (potentially for use as a trigger in an automation), the `scene_changed` event informs the user that all members of a given scene have had their states' changed (and how the state has been changed).

**Comment by gwww** [comment]
Scenario 2, I'm with you all the way up to step 5. Why not fire a `upb.scene_goto` event?

**Comment by tdejneka** [comment]
Sure, it could be that but I had trouble with making "goto" not sound like a command. Instead of `scene_activate` we have `scene_activated`. Instead of `scene_goto` we have `scene_goneto`? Ugh. hat's why I suggested `scene_changed` since it effectively expresses what's happened if you use Goto and (optionally) FadeRate.

**Comment by gwww** [comment]
How about we call good enough. I thought perhaps we were talking about functionality being different depending on how the command was received. For semantics of names we can change it later.

As soon as you have tested the new events, feel free to mark this as closed.

**Comment by tdejneka** [comment]
Using this automation:
```
- alias: 'UPB event'
  trigger:
  - platform: event
    event_type: upb.scene_activated
    event_data:
      entity_id: scene.all_exterior
  action:
  - service: persistent_notification.create
    data_template:
      message: 'entity_id: {{trigger.event.data.entity_id}}'
      title: 'UPB Scene Activated'
```
it fails to trigger (with or without the `event_data`) This time I remembered to check the system log and found error messages. 

I had pushed the button four times (activate, deactivate, activate, deactivate) and each time it produced the same error message. 
> Error doing job: Exception in callback SerialTransport._read_ready()

Here are the last two error messages (representing the 3rd and 4th button presses to activate/deactivate the link):

```
2020-02-03 15:09:48 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback SerialTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/site-packages/serial_asyncio/__init__.py", line 106, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.7/site-packages/upb_lib/proto.py", line 100, in data_received
    self._got_data_callback(line[2:])
  File "/usr/local/lib/python3.7/site-packages/upb_lib/upb.py", line 126, in _got_data
    self._message_decode.decode(data)
  File "/usr/local/lib/python3.7/site-packages/upb_lib/message.py", line 80, in decode
    handler(self)
  File "/usr/local/lib/python3.7/site-packages/upb_lib/links.py", line 94, in _activate_handler
    self._activate_deactivate(msg, UpbCommand.ACTIVATE)
  File "/usr/local/lib/python3.7/site-packages/upb_lib/links.py", line 91, in _activate_deactivate
    link._update_light_levels(upb_cmd, level)
  File "/usr/local/lib/python3.7/site-packages/upb_lib/links.py", line 67, in _update_light_levels
    self.setattr("last_change", time())
  File "/usr/local/lib/python3.7/site-packages/upb_lib/elements.py", line 44, in setattr
    self._call_callbacks()
  File "/usr/local/lib/python3.7/site-packages/upb_lib/elements.py", line 33, in _call_callbacks
    callback(self, self._changeset)
  File "/config/custom_components/upb/__init__.py", line 100, in _element_callback
    self._element_changed(element, changeset)
  File "/config/custom_components/upb/scene.py", line 65, in _element_changed
    command = changeset["last_change"]["command"]
TypeError: 'float' object is not subscriptable

2020-02-03 15:12:31 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback SerialTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/site-packages/serial_asyncio/__init__.py", line 106, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.7/site-packages/upb_lib/proto.py", line 100, in data_received
    self._got_data_callback(line[2:])
  File "/usr/local/lib/python3.7/site-packages/upb_lib/upb.py", line 126, in _got_data
    self._message_decode.decode(data)
  File "/usr/local/lib/python3.7/site-packages/upb_lib/message.py", line 80, in decode
    handler(self)
  File "/usr/local/lib/python3.7/site-packages/upb_lib/links.py", line 97, in _deactivate_handler
    self._activate_deactivate(msg, UpbCommand.DEACTIVATE)
  File "/usr/local/lib/python3.7/site-packages/upb_lib/links.py", line 91, in _activate_deactivate
    link._update_light_levels(upb_cmd, level)
  File "/usr/local/lib/python3.7/site-packages/upb_lib/links.py", line 67, in _update_light_levels
    self.setattr("last_change", time())
  File "/usr/local/lib/python3.7/site-packages/upb_lib/elements.py", line 44, in setattr
    self._call_callbacks()
  File "/usr/local/lib/python3.7/site-packages/upb_lib/elements.py", line 33, in _call_callbacks
    callback(self, self._changeset)
  File "/config/custom_components/upb/__init__.py", line 100, in _element_callback
    self._element_changed(element, changeset)
  File "/config/custom_components/upb/scene.py", line 65, in _element_changed
    command = changeset["last_change"]["command"]
TypeError: 'float' object is not subscriptable
```

**Comment by gwww** [comment]
Ahhhh. Try this. Edit the manifest.json in your upb directory. Change the required version of upb_lib to 0.1.1

When I uploaded the new code forgot to update the lib version.

**Comment by tdejneka** [comment]
That fixed it! I can confirm the automation now triggers on activated/deactivated events. (and entity_data is optional).

Still a few more tests to do before this thread can be closed.

**Comment by tdejneka** [comment]
I tested triggeriing on `scene_goto` event using the following automation:
```
- alias: "Scene changed"
  trigger:
    platform: event
    event_type: upb.scene_goto
  action:
    service: system_log.write
    data_template:
      level: warning
      message: "Changed '{{trigger.event.data.entity_id}}' Data '{{trigger}}'"
```
I generated the Goto command using Developer tools > Services like this:
![Screenshot from 2020-02-03 21-59-29](https://user-images.githubusercontent.com/44732909/73710101-0db07a00-46d1-11ea-9f29-df481f1cca89.png)

The lights associated with the responded correctly to the command, changing to level 75 at rate=4 (~5 seconds). The automation triggered and reported the following message:
> Changed 'scene.all_exterior' Data '{'platform': 'event', 'event': <Event upb.scene_goto[L]: entity_id=scene.all_exterior, level=75>}'

The only hiccup is it overlooks to mention `rate=4`. Is this by design or a bug?

**Comment by tdejneka** [comment]
Repeated the tests (shown in my previous post) with version 0.0.7-alpha and can confirm it now reports `rate`.

> Changed 'scene.all_exterior' Data '{'platform': 'event', 'event': <Event upb.scene_goto[L]: entity_id=scene.all_exterior, level=75, **rate=4**>}'

Question:
The `upb_link_goto` service has a parameter called `brightness_pct`. However in the reported event.data it is called `level`. Should they not share the same name?

**Comment by gwww** [comment]
Fixed `level`, `brightness_pct` will be in next release.

**Comment by tdejneka** [comment]
Tested with 0.0.9-alpha and confirmed `event.data` now reports `brightness_pct` and `rate`.

> Changed 'scene.all_exterior' Data '{'platform': 'event', 'event': <Event upb.scene_goto[L]: entity_id=scene.all_exterior, brightness_pct=75, rate=5>}'
