### ISSUE TITLE
component configuration not working cleanly within HASS

### ISSUE THREAD

**Issue by bbrendon** [gwww/hass-upb#2]
It seems like it doesn’t co-mingle with other integrations nicely. One glaring thing is that `config_check` fails when the UPB component is enabled but strangely HASS still works when only UPB is configured. For example, this fails but HASS will actually start.

`/opt/python-venvs/hass/bin/hass -c /opt/hass-upb --script check_config`

…but when I run it in production it all falls apart.

```
2020-02-01 09:50:41 ERROR (MainThread) [homeassistant.config] Invalid config for [upb]: expected a dictionary for dictionary value @ data['upb']. Got [OrderedDict([('url', 'serial:///dev/ttyS1:480
2020-02-01 09:50:41 ERROR (MainThread) [homeassistant.setup] Setup failed for upb: Invalid config.
```

Also, other integrations start throwing errors like …

```
  File "/opt/python-venvs/hass/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 147, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

It seems like the UPB configuration is leaking out of it's configuration container if that makes any sense. I don't really quite understand what's happening but that would be my lay-man's guess.

**Comment by gwww** [comment]
I'm thinking this is a Hass bug. Asked for help on Discord #dev channel.

In my testing the very simplest of configs, with pretty much just `upb` stuff in it fails a config_check. It does run in hass proper. 

I do not get any crashes as is reported in issue. I've tried with two integrations, `upb` and `elkm1`.

If you can try to create a minimal config see if you can figure out more that would be useful.

**Comment by bbrendon** [comment]
I looked at this a bit. My python is very basic but maybe...

Since upb is an extension of light and there isn't a upb domain in HASS, maybe it should be 
`PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend({` ....

Part of my UPB stuff is linked below. I don't know what half of the stuff means. I just copied another integration.

https://github.com/bbrendon/hass/blob/master/custom_components/upb/light.py

**Comment by gwww** [comment]
My understand is no, not PLATFORM_SCHEMA. What we are doing is a CONFIG_SCHEMA, meaning a top level configuration. The `upb` keyword is top level with its config within it. I've been through this already with the ElkM1 integration. See this: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/elkm1/__init__.py#L127-L130

**Comment by gwww** [comment]
Well, turned out to be a dumb error. I had left a `PLATFORM_SCHEMA` import in the file and boom! Fixed.
