### ISSUE TITLE
feature request: flash support

### ISSUE THREAD

**Issue by bbrendon** [gwww/hass-upb#4]
![image](https://user-images.githubusercontent.com/6364477/73719066-186c0e80-46d3-11ea-8b86-23c36a1aee2f.png)

Light goes on, no flashing.

**Comment by gwww** [comment]
The `light.turn_on` `flash` attribute is not supported. A custom blink service for the light is supported. Now, I could support the `turn_on`, but we'd have to pick `rate`s for long and short.

**Comment by bbrendon** [comment]
I think it might be useful to support the standard flash attribute because other templates using the standard mechanism would work out of the box. 

This looks like I did 50/100 previously.

```
        if flash:
            # flashing is full on/off. so lets just say its on.
            bright_pct = 255
            # upb-cli -n 22 -i 83 -t device -c blink -b 50  --send -p /dev/ttyS1
            if flash == "short":
                flash_val = 50
            if flash == "long":
                flash_val = 100
            upb_command(' -i ' + self._id + ' -t device -c blink -b ' + str(flash_val) + ' --send' )
        else:
            upb_command(' -i ' + self._id + ' -t device -c goto -l ' + str(bright_pct) + ' --send' )
```

**Comment by gwww** [comment]
Will be in next releases. Used 50/100.

**Comment by bbrendon** [comment]
Flash short/long could also be configuration options as well. 50/100 could be the default.

**Comment by gwww** [comment]
If you could test and close that'd be great :) 

You can open a feature request for config for the short/long params if you care to. Not high on the list as there's still basic functionality to go and lots of testing.

**Comment by bbrendon** [comment]
Works.
