### ISSUE TITLE
Light entity's state is unchanged after using upb_light_fade_start service.

### ISSUE THREAD

**Issue by tdejneka** [gwww/hass-upb#5]
Using version 0.0.7-alpha, I ran the following test:
![Screenshot from 2020-02-04 06-50-12](https://user-images.githubusercontent.com/44732909/73742745-16c63900-471b-11ea-9759-4665ec600648.png)
The light proceeded to brighten at the specified rate.

Before it reached the target brightness of 100, I ran the following:
![Screenshot from 2020-02-04 06-55-30](https://user-images.githubusercontent.com/44732909/73742904-6efd3b00-471b-11ea-96a4-410efb2c84e0.png)
The light stopped brightening (and remained on at a level short of 100). Therefore the two services appear to work correctly. However, in **Developer tools > States**, the state of `light.family_ceilinglight` is `off` (and its `status` attribute is `0`).

It would appear that the UPB integration is unaware of the light's state when using `upb_light_fade_start`.

**Comment by gwww** [comment]
On fade_start I purposely did not update. What to update it to?

On fade_stop I also purposely did not update, but was hoping that the device would send a status update. Since the light level could be anything, I need to send a status update to the device.

When I get around to implementing on a link I'm guess the only thing to do is poll all devices in the scene to get their new status. Yuck! This is really yucky because a status update for ~10 devices takes 5 seconds and is a lot of UPB traffic. What makes is double bad is that if  people use this as I would guess, they will be sending multiple start_fade commands as they adjust the scene's level.

Other thoughts on how to do this?

**Comment by gwww** [comment]
Another issue not sure how to handle is what happens when a `fade_start` is issued and no `fade_stop`?

**Comment by tdejneka** [comment]
Currently, using `light.turn_on` with a `brightness_pct` (75) and a `transition` (10) will make the light slowly turn on to the desired brightness level. The entity's state is immediately set to `on` and its `status` attribute indicates 75. I assume that, under the hood, the UPB integration is using Goto to perform this task.

According to the documentation, Goto and Fade Start are virtually the same:
![Screenshot from 2020-02-04 08-40-08](https://user-images.githubusercontent.com/44732909/73753484-cbb72080-4730-11ea-854e-3334fde3a950.png)

Here's how they differ:
> Note: The only difference between the Fade Start Command and the Goto Command is that non-
dimming type devices shall ignore the Fade Start Command.

If that's the only difference then the UPB integration should handle Fade Start the same way it currently handles Goto: the entity's state and status attribute should be set the moment Fade Start begins.

You may ask "What if a Fade Stop is issued while Fade Start (or even Goto) is underway?" I don't think there's an easy solution other than to issue a ReportState command on the heels of a Fade Stop. If not that then the entity's displayed state may be out of sync with the physical device's actual state.

Regarding your question, if you don't issue a Fade Stop then Fade Start simply completes its task (like Goto).

**Comment by gwww** [comment]
Alright! `fade_start` sets light to the brightness. `fade_stop` request status from light.

For links, `fade_start` could set brightness for each of the lights in the scene. `fade_stop`?? Sure it can request status, but that's potentially a lot of lights. I guess, "just do it" and warn people when using fade on links that there is potentially a lot of UPB traffic.

**Comment by tdejneka** [comment]
I don't see an alternative to following up a Fade Stop with a Report State. Given a scene with many members, it will definitely generate a fair bit of traffic. It's the nature of the UPB beast and users will have to keep this side-effect in mind. Whatever "storm" of responses the Report State might generate after a Fade Stop is only likely to occur while I'm beta-testing the UPB integration; not likely it'll ever get exercised afterwards.

Frankly, I've yet to envision a need to make all my (say) interior lights start a fade over such a long duration that I might need to interrupt it with a Fade Stop. It's a 'nice to have' but, at least in my home, there's no practical application for it. 

In contrast, activating/deactivating a scene will happen at least three times every day.

**Comment by tdejneka** [comment]
Using 0.0.9-alpha, I've confirmed all of the following:

Using `upb.light_fade_start` will:
- set the device to the desired `brightness_pct` at the specified `rate`
- immediately set the corresponding entity to the desired `brightness_pct` and `rate`

If the `rate` is a long duration, the device's brightening/dimming can be be interrupted using `upb.upb_fade_stop`. It will:
- halt the brightening/dimming action
- set the corresponding entity to whatever is the device's current `state` and `brightness_pct`

---
Observations:

I assume the `Fade Stop` command is being followed by a `Report State` command in order to acquire the device's current status. A side-benefit of this procedure is that the reply to `Report State` is heard by other PIMs that may be listening. In my case, I have a second PIM (connected to Premise) and it heard the status reply and updated its instance of the same device (for this test it was my patio light).

In contrast, issuing a `Fade Start`, or `Goto`, may be heard by other PIMs but it does not (necessarily) cause them to update the status of the entities they manage. For example, Premise's UPB driver does not perform any action when it hears a `Fade Start`, `Fade Stop`, or `Goto` that it did not initiate; it only acts on status reports it may receive.  As a consequence, anyone wishing to maintain two or more separate systems, each with their own PIM, will have to deal with the challenge of maintaining synchronized states.
