### ISSUE TITLE
feature req: upb_ prefix

### ISSUE THREAD

**Issue by bbrendon** [gwww/hass-upb#7]
https://github.com/gwww/hass-upb/blob/8b970c3133755cf60bc1447d00b472dcecd84da2/custom_components/upb/__init__.py#L67

Is it possible to make this 
```
 return "upb_" + self._element.name
```

...or a configuration option? This would be so handy because I could just do my upstart edits, export, restart hass and not have to hunt for whatever I changed in upstart and modify the entity_id in HASS to have the `upb_` prefix.

**Comment by tdejneka** [comment]
I don't know if this will help you but have a look at `Configuration > Entities`. The `Integration` column will indicate `upb` for each entity that uses the UPB integration. If you enter `upb` in the Search bar, it will constrain the list. You can then sort the list by either `Name` or `Entity ID` (by clicking the column heading).

**Comment by bbrendon** [comment]
A little helpful, but still more work.

**Comment by gwww** [comment]
An option, is well, not an option. I've watched many of the Home Assistant architecture discussions and a prefix won't fly. I don't want the prefix of "UPB" to be a default either. So given that I think closing this is appropriate. I will let you add another comment and then close.

One option you do have is to write a wee python script that takes the upe file and doctors the names as you wish. If you want a starting point take a look at `upb_lib/parse_upstart.py`.

**Comment by bbrendon** [comment]
I'm not saying the default should be `upb_`. I would find it very useful to be able to change it. I'm pretty sure you're correct that upstream won't allow `upb_` to be default either. I'm not sure if they would deny changing the default with a config option though.

Anyway, I've done my 0.02. Feel free to close if this is off the table.

**Comment by gwww** [comment]
I'm pretty sure that they will not allow a config option to change default. If you can determine otherwise I'd be OK to add the feature. Closing for now.

**Comment by bbrendon** [comment]
@gwww you're right. balloob said no. I got shutdown :(
Oh well, I tried. Sounds like someday it might be possible when the GUI/options get more advanced but not now.
