### ISSUE TITLE
Feature Request: Report State configuration option

### ISSUE THREAD

**Issue by tdejneka** [gwww/hass-upb#8]
This Feature Request falls into the category of 'nice to have' and is useful only to a minority of users (like me).

Currently, the integration sends the following UPB commands without needing to ask devices to report their (new) state:
- `Goto`
- `Fade Start`
- `Blink`

The reason it isn't requested is obvious because the integration is the _source_ of the desired state/action.

There is one exception and it's the `Fade Stop` command. The integration doesn't know the device's new state at the moment it stops fading. Therefore, after issuing a `Fade Stop`, the integration follows up with a `Report State` command. Upon receiving the device's reply, it learns the device's new state.

The side-benefit of sending `Report State` is if there's another PIM listening it will also be apprised of the device's new state. In other words, in a multi-PIM environment, the appended `Report State` command ensure all PIMs are informed of changes.

This Feature Request is to provide a configuration option that makes the integration append a `Report State` command to `Goto`, `Fade Start`, and `Blink` commands. The default state of this option will naturally be `false` because most users, using a single PIM controlled by Home Assistant, don't need it (it would generate superfluous UPB status traffic). Users with a multi-PIM environment can set the option to `true` and accept the extra status traffic as being the only means to keep all PIMs "in-sync".

```
upb:
  url: serial:///dev/ttyUSB0:4800
  file_path: ./upb.upe
  report_state: true # optional, default is false
```

**Comment by gwww** [comment]
A couple of things. Can we split off the "extra nice-to-have". I think this should be done.

Fade-stop already asks for status since there is no way to infer status when a fade-stop is issued. Goto/blink infer their status.

As for goto/blink status maybe the way to handle that is to pass flags into upb_lib to configure it to ask for state after certain operations. Not everyone will require this feature. Then again flags may be overthinking.

**Comment by tdejneka** [comment]
OK, I'll move the `Report State` service call to a separate Feature Request.

**Comment by gwww** [comment]
Will be in 0.4.4 version of the library. Flag is `report_state`.

Report state will be asked for, when turned on, for goto, fade start, and blink. Lights only, not links.
