### ISSUE TITLE
Feature Request: Report State service

### ISSUE THREAD

**Issue by tdejneka** [gwww/hass-upb#9]
It would be useful to have a `upb.upb_report_state` service to allow users to request the current state of one or more devices. If the state of a device is in question, the new service allows one to ask for an update.

---

Here's one potential use of this new service. When the UPB integration uses either `Goto` or `Fade Start`, it immediately sets the corresponding entity's brightness to the target level. For all cases where the fade_rate is brief (a few seconds) this is a fair compromise and (within short order) reflects the truth. However, lets say `Goto` sets the light to a level of 100 in _5 minutes_. Reporting the entity's is at level 100 _immediately_ doesn't reflect reality. The device will slowly ramp from 0 to 100 over a period of 5 minutes so the entity's brightness level varies over time.

In the (admittedly) rare case where you would want to know the device's actual level during its ramping period, you could use an automation to poll the device using `upb.upb_report_state`.

**Comment by gwww** [comment]
Feature added (actually quite some time ago). See d496d435ee65999e0e72f72085161576d7b6e58a
